name: cpfs_marketplace
description: Cell Phones For Soldiers Marketplace App
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  amplify_flutter: ^2.0.0
  amplify_auth_cognito: ^2.0.0
  amplify_api: ^2.0.0
  go_router: ^14.0.0
  provider: ^6.1.0
  flutter_svg: ^2.0.9
  cached_network_image: ^3.3.0
  url_launcher: ^6.2.0
  amplify_storage_s3: ^2.6.1
  geolocator: ^10.0.1
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  google_maps_flutter_android: ^2.5.0
  google_maps_flutter_ios: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/data/
    - assets/data/cpfs-drop-off-locations.json
    - assets/data/homeless-shelters.json
    - assets/data/vso-offices.json
  # fonts:
  #   - family: OpenSans
  #     fonts:
  #       - asset: assets/fonts/OpenSans-Regular.ttf
  #       - asset: assets/fonts/OpenSans-Bold.ttf
  #         weight: 700
  #       - asset: assets/fonts/OpenSans-SemiBold.ttf
  #         weight: 600
